# deployment/docker_compose.yml

version: "3.9"

services:
  namo_app:
    build:
      context: .
      dockerfile: deployment/Dockerfile
    container_name: namo_container
    ports:
      - "8000:8000"
    environment:
      - MULTIVERSE_ENABLED=true
      - AICP_PROTOCOL_VERSION=3.14
