name: CI
on: [push, pull_request]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Run basic checks
        run: |
          python -m pip install -U pip
          python - <<'PY'
          import pathlib
          assert pathlib.Path('sanitized_core').exists(), 'sanitized_core/ missing'
          PY
